Algoritmo "Creuza04"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Rai
// Data atual  : 11/10/2025
Var
   Imposto, preco: Real

Inicio
      Escreva("Qual o preço do produto? US$")
      Leia(Preco)
      Imposto <- Preco * 0.6
      Escreva("O preço dos impostos vai ser US$", Imposto:5:2)

Fimalgoritmo