Algoritmo "Creuza 03"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Rai
// Data atual  : 11/10/2025
Var
   F, C: Real


Inicio
      Escreva("Quantos Graus fahrenheit estão agora? ")
      Leia(F)
      C <- (F - 32)/1.8
      Escreva("Certo, então é a mesma coisa que ", C:1:1 , " graus celsius.")


Fimalgoritmo