Algoritmo "Creuza02"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Rai
// Data atual  : 11/10/2025
Var
   Reais, Dolares: real


Inicio
      Escreva("Quantos reais eu tenho? ")
      Leia(Reais)
      Dolares <- Reais / 5.53
      Escreva("Nossa, no câmbio disseram que com isso só vou ter ", Dolares, " dolares!")

Fimalgoritmo