Algoritmo "Vai aprender a programar sim"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Início de tudo
// Autor(a)    : Rai
// Data atual  : 04/10/2025
Var
  msg: caractere
  prof: caractere
Inicio
 msg <- "Olá, Mundoooooo!"
 prof <- "Gustavo Guanabara"
 Escreval (msg)
 escreval ("Cara que daora!!!!")
 Escreva ("Obrigado pela aula, ", prof)
 
Fimalgoritmo